# Generated by Django 5.1.7 on 2025-05-26 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.ImageField(upload_to="grading_images/")),
                ("user_id", models.BigIntegerField()),
                (
                    "upload_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("image_name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "image",
            },
        ),
        migrations.CreateModel(
            name="GradingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("final_grade", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("user_id", models.BigIntegerField()),
                ("confidence", models.FloatField()),
                ("detected_label", models.CharField(max_length=50)),
                ("source", models.CharField(default="upload", max_length=10)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grading.image"
                    ),
                ),
            ],
            options={
                "db_table": "grading_gradingresult",
                "ordering": ["-created_at"],
            },
        ),
    ]
