# Generated by Django 5.1.7 on 2025-05-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=models.ImageField(upload_to=""),
        ),
    ]
