# Generated by Django 5.1.7 on 2025-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0002_alter_image_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="original_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
