# Generated by Django 5.1.7 on 2025-06-01 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0003_image_original_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="original_url",
        ),
    ]
