# args.yaml（示例）
input_size: [640, 640]       # 对应训练配置中的 imgsz: 640（输入图像尺寸）
mean: [0.485, 0.456, 0.406]  # 归一化均值（与YOLOv8默认一致，无需修改）
std: [0.229, 0.224, 0.225]   # 归一化标准差（与YOLOv8默认一致，无需修改）
conf_threshold: 0.3          # 置信度阈值（过滤低置信度检测框，可根据需求调整）